# Generated by Django 4.0.5 on 2022-06-24 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_site', '0002_alter_specialist_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialist',
            name='specialties',
        ),
        migrations.AddField(
            model_name='specialist',
            name='specialties',
            field=models.ManyToManyField(null=True, to='clinic_site.specialty', verbose_name='Напрямки'),
        ),
    ]
